
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yiqfsetkcnvudalyntvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpcWZzZXRrY252dWRhbHludHZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMTQyNDEsImV4cCI6MjA1OTU5MDI0MX0.URMjHKwAZcIY6HEg0AO5diBXlDISw6k84ZbnMK-4maU";

// Get token from localStorage
const getAuthToken = () => {
  try {
    if (typeof window === 'undefined') return '';

    const tokenString = localStorage.getItem('sb-yiqfsetkcnvudalyntvw-auth-token');
    if (tokenString) {
      try {
        const tokenData = JSON.parse(tokenString);
        return tokenData?.access_token || '';
      } catch (e) {
        console.error('Error parsing auth token:', e);
        return '';
      }
    }
    return '';
  } catch (error) {
    console.error('Error retrieving auth token:', error);
    return '';
  }
};

// Create client with dynamic auth headers
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storage: typeof window !== 'undefined' ? localStorage : undefined
  },
  global: {
    headers: {
      // Forward auth token to all supabase requests including edge functions
      Authorization: `Bearer ${getAuthToken()}`
    }
  }
});

// Add an event listener to update headers when auth state changes
if (typeof window !== 'undefined') {
  supabase.auth.onAuthStateChange(() => {
    // Update global headers with new token
    const token = getAuthToken();
    // Instead of using the non-existent setAuth method, update the global headers directly
    supabase.rest.headers.authorization = `Bearer ${token}`;
  });
}
